{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Journal",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", service_name=\"systemd-journal\"} != `loki` != `traceID`"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": {
    "content": "I must not fear.\nFear is the mind-killer.\nFear is the little-death that brings total obliteration.\nI will face my fear.\nI will permit it to pass over me and through me.\nAnd when it has gone past, I will turn the inner eye to see its path.\nWhere the fear has gone there will be nothing. Only I will remain."
   }
  },
  {
   "title": "Temperature",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "avg(node_hwmon_temp_celsius)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"system\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read/write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_disk_write_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) / 5 / 60 / 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) / 5 / 60 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}